version: '2'
services:
  db:
    image: mongo:3.0.2
    ports:
      - "27017:27017"
    
  web:
    image: tomcat
    ports: 
      - "8080:8080"
    volumes:
      - ./target/SGA_REST_DataIngest.war:/usr/local/tomcat/webapps/SGA_REST_DataIngest.war
    links:
      - db
