language: java
jdk:
  - oraclejdk8
sudo: false
install: true

script: cd "SGA_Data_Ingestor_Build" && mvn -e clean install

branches:
  only:
    - Data_ingestor
notifications:
  email:
    - vikas1590@gmail.com
    - raghava1990@gmail.com



