language: python
python:
  - "3.4"

env:
  - FLASK=0.11.1

services : mongodb

sudo: true

before_install:
  - pip install flask==$FLASK coverage
  - pip install requirements.txt

install: true

script: cd "SGA_REST_DataIngest" && mvn -e clean install

before_deploy:
  - cd ..
  - zip -r SGA_Sangam_WeatherApp.zip SGA_REST_DataIngest SGA_Rest_login appspec.yml || true
  - mkdir -p "dpl_cd_upload"
  - mv SGA_Sangam_WeatherApp.zip dpl_cd_upload/SGA_Sangam_WatherApp.zip || true

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    local_dir: dpl_cd_upload
    bucket: teamsangam
    region: us-west-2
    skip_cleanup: true
    acl: public_read
    detect_encoding: true
    on:
      repo: airavata-courses/TeamSangam
      all_branches: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: teamsangam
    key: SGA_Sangam_WeatherApp.zip
    bundle_type: zip
    application: SGA-TeamSangam
    deployment_group: TeamSangam
    region: us-west-2
    on:
      repo: airavata-courses/TeamSangam
      all_branches: true

after_deploy:
  - echo "Deploy steps completed successfully."

branches:
  only:
    - Development

notifications:
  email:
    - vikas1590@gmail.com
    - raghava1990@gmail.com
    - rajasimha1991@gmail.com
