language: python
python:
  - "3.4"

env:
  - FLASK=0.11.1

services : mongodb

sudo: true

before_install:
  - pip install flask==$FLASK coverage


install: true

script: cd "SGA_REST_DataIngest" && mvn -e clean install

branches:
  only:
    - Development

notifications:
  email:
    - vikas1590@gmail.com
    - raghava1990@gmail.com
    - rajasimha1991@gmail.com
