language: python
python:
  - "3.4"

env:
  - FLASK=0.11.1

services:
  - mysql
  - mongodb
  - rabbitmq

sudo: true

before_install:
  - pip install flask==$FLASK coverage
  - pip install -r requirements.txt

install: true

before_script:
  - cd env_scripts
  - source props.sh
  - cd ..

script: 
  - cd ../SGA_REST_Registry && mvn -e clean install -Dmaven.test.skip=true

before_deploy:
  - cd ..
  - pwd
  - ls
  - tar -cf SGA_Sangam_Registry.tar . || true
  - mkdir -p "dpl_cd_upload"
  - ls
  - mv SGA_Sangam_Registry.tar dpl_cd_upload/SGA_Sangam_Registry.tar || true

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    local_dir: dpl_cd_upload
    bucket: sga-sangam-dataingestor
    region: us-east-1
    skip_cleanup: true
    acl: public_read
    detect_encoding: true
    on:
      repo: airavata-courses/TeamSangam
      branch: registry

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: sga-sangam-dataingestor
    key: SGA_Sangam_Registry.tar
    bundle_type: tar
    application: SGA-Sangam-stormClustering
    deployment_group: SGA-Sangam-stormClustering
    region: us-east-1
    on:
      repo: airavata-courses/TeamSangam
      branch: registry

after_deploy:
  - echo "Deploy steps completed successfully."

branches:
  only:
    - registry

notifications:
  email:
    - vikas1590@gmail.com
    - rajasimha1991@gmail.com
    - raghava1990@gmail.com
